# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SnapshotTestingTut' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SnapshotTestingTut

  target 'SnapshotTestingTutTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'SnapshotTesting'
  end

  target 'SnapshotTestingTutUITests' do
    # Pods for testing

  end

end
